export default [
  { path: "/", file: "routes/_index.jsx", showInNav: false },
  {
    path: "/courses",
    file: "routes/courses.jsx",
    showInNav: true,
    label: "courses",
    navTo: "/courses/frontend",
    children: [{ path: ":tab", file: "routes/courses.$tab.jsx" }],
  },
  {
    path: "/courses/:tab/:courseId",
    file: "routes/courses.$tab.$courseId.jsx",
    showInNav: false,
  },
  {
    path: "/courses/:tab/:courseId/preview",
    file: "routes/courses.$tab.$courseId.preview.jsx",
    showInNav: false,
  },
  { path: "/blog", file: "routes/blog.jsx", showInNav: true, label: "blogs" },
  { path: "/blog/:blogId", file: "routes/blog_.$blogId.jsx", showInNav: false },
  {
    path: "/about",
    file: "routes/about.jsx",
    showInNav: true,
    label: "about us",
  },
  {
    path: "/contact",
    file: "routes/contact.jsx",
    showInNav: true,
    label: "contact",
  },
  {
    path: "/login",
    file: "routes/login.jsx",
    showInNav: true,
    label: "login | signup",
  },
  { path: "/profile", file: "routes/profile.jsx", showInNav: false },
  { path: "/logout", file: "routes/logout.jsx", showInNav: false },
  { path: "/cart", file: "routes/cart.jsx", showInNav: false },
  { path: "/checkout", file: "routes/checkout.jsx", showInNav: false },
  { path: "/invoice/:invoiceNumber", file: "routes/invoice.$invoiceNumber.jsx", showInNav: false },
  {
    path: "/admin",
    file: "routes/admin/index.jsx",
    showInNav: true,
    label: "admin",
    children: [
      {
        path: "/admin/dashboard",
        file: "routes/admin/dashboard.jsx",
        label: "dashboard",
      },
      { path: "/admin/users", file: "routes/admin/users.jsx", label: "users" },
      {
        path: "/admin/courses",
        file: "routes/admin/courses.jsx",
        label: "cursos",
      },
      {
        path: "/admin/blogs",
        file: "routes/admin/blogs.jsx",
        label: "publicaciones",
      },
    ],
  },
];
