// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/test": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/courses/:tab": {
    params: {
      "tab": string;
    };
  };
  "/:name": {
    params: {
      "name": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/contact" | "/test" | "/users" | "/courses" | "/courses/:tab" | "/:name";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/test.jsx": {
    id: "routes/test";
    page: "/test";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/courses.jsx": {
    id: "routes/courses";
    page: "/courses" | "/courses/:tab";
  };
  "routes/courses.$tab.jsx": {
    id: "routes/courses.$tab";
    page: "/courses/:tab";
  };
<<<<<<< HEAD
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/contact": typeof import("./app/routes/contact.jsx");
  "routes/test": typeof import("./app/routes/test.jsx");
  "routes/users": typeof import("./app/routes/users.jsx");
  "routes/$name": typeof import("./app/routes/$name.jsx");
  "routes/courses": typeof import("./app/routes/courses.jsx");
  "routes/courses.$tab": typeof import("./app/routes/courses.$tab.jsx");
=======
  "routes/$name.jsx": {
    id: "routes/$name";
    page: "/:name";
  };
>>>>>>> a97f203b156035e689d88cff21e69e6fd504562d
};