// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/courses/:tab": {
    params: {
      "tab": string;
    };
  };
  "/courses/:tab/:courseId": {
    params: {
      "tab": string;
      "courseId": string;
    };
  };
  "/courses/:tab/:courseId/preview": {
    params: {
      "tab": string;
      "courseId": string;
    };
  };
  "/blog": {
    params: {};
  };
  "/blog/:id": {
    params: {
      "id": string;
    };
  };
  "/about": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/invoice/:invoiceNumber": {
    params: {
      "invoiceNumber": string;
    };
  };
  "/admin": {
    params: {};
  };
  "/admin/admin/dashboard": {
    params: {};
  };
  "/admin/admin/users": {
    params: {};
  };
  "/admin/admin/courses": {
    params: {};
  };
  "/admin/admin/blogs": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/courses" | "/courses/:tab" | "/courses/:tab/:courseId" | "/courses/:tab/:courseId/preview" | "/blog" | "/blog/:id" | "/about" | "/contact" | "/login" | "/profile" | "/logout" | "/cart" | "/checkout" | "/invoice/:invoiceNumber" | "/admin" | "/admin/admin/dashboard" | "/admin/admin/users" | "/admin/admin/courses" | "/admin/admin/blogs";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/courses.jsx": {
    id: "routes/courses";
    page: "/courses" | "/courses/:tab";
  };
  "routes/courses.$tab.jsx": {
    id: "routes/courses.$tab";
    page: "/courses/:tab";
  };
  "routes/courses.$tab.$courseId.jsx": {
    id: "routes/courses.$tab.$courseId";
    page: "/courses/:tab/:courseId";
  };
  "routes/courses.$tab.$courseId.preview.jsx": {
    id: "routes/courses.$tab.$courseId.preview";
    page: "/courses/:tab/:courseId/preview";
  };
  "routes/blog.jsx": {
    id: "routes/blog";
    page: "/blog";
  };
  "routes/blog.$blogId.jsx": {
    id: "routes/blog.$blogId";
    page: "/blog/:id";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/profile.jsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/logout.jsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/checkout.jsx": {
    id: "routes/checkout";
    page: "/checkout";
  };
  "routes/invoice.$invoiceNumber.jsx": {
    id: "routes/invoice.$invoiceNumber";
    page: "/invoice/:invoiceNumber";
  };
  "routes/admin/index.jsx": {
    id: "routes/admin/index";
    page: "/admin" | "/admin/admin/dashboard" | "/admin/admin/users" | "/admin/admin/courses" | "/admin/admin/blogs";
  };
  "routes/admin/dashboard.jsx": {
    id: "routes/admin/dashboard";
    page: "/admin/admin/dashboard";
  };
  "routes/admin/users.jsx": {
    id: "routes/admin/users";
    page: "/admin/admin/users";
  };
  "routes/admin/courses.jsx": {
    id: "routes/admin/courses";
    page: "/admin/admin/courses";
  };
  "routes/admin/blogs.jsx": {
    id: "routes/admin/blogs";
    page: "/admin/admin/blogs";
  };
};