// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/courses": {
    params: {};
  };
  "/courses/:tab": {
    params: {
      "tab": string;
    };
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/login" | "/courses" | "/courses/:tab" | "/contact";
  };
  "routes/login.jsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/courses.jsx": {
    id: "routes/courses";
    page: "/courses" | "/courses/:tab";
  };
  "routes/courses.$tab.jsx": {
    id: "routes/courses.$tab";
    page: "/courses/:tab";
  };
  "routes/contact.jsx": {
    id: "routes/contact";
    page: "/contact";
  };
};